# styling: https://starship.rs/advanced-config/#style-strings
# prompt customization: https://starship.rs/config/#prompt

format = """
$directory $git_branch $git_state $git_commit $cmd_duration $time
$character """

[directory]
truncation_length = 3
truncate_to_repo  = false
truncation_symbol = "../"
format = "[$path](bold fg:#35b77a)[$read_only]($read_only_style)"

[cmake]
disabled = true

[character]
#https://getemoji.com/
success_symbol = "ğŸ’"
error_symbol = "ğŸ‘»"

